### PR TITLE
convert to octane addon

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by flashios09** [comment]
hi @NullVoxPopuli , why you have dropped support for **Module Unification** ?

**Comment by NullVoxPopuli** [comment]
I haven't dropped support for it, but as I want _this_ addon to be used by as many people as possible, I needed to switch it to classic layout.

**Comment by flashios09** [comment]
> I haven't dropped support for it 

So we can still use the query params service with *MU* ?

**Comment by NullVoxPopuli** [comment]
yeah, MU and non-MU doesn't matter for this addon :)

**Pull request merged**
